baseURL = "https://lucywang000.github.io/clj-statecharts"
languageCode = "en-us"
title = "clj-statecharts"
theme = "book"

[params]

BookMenuBundle = "/menu"
BookRepo = "https://github.com/lucywang000/clj-statecharts"
BookEditPath = "blob/master/docs/content"
