name: publish

on: [push]

jobs:
  test:
    # ubuntu 18.04 comes with lein + java8 installed
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Run Tests
        run:
          lein kaocha

  docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: Store gh token
        run: |
          cat >~/.netrc<<EOF
          machine github.com
          login lucywang000
          password ${{ secrets.GITHUB_TOKEN }}
          EOF

      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Deploy to GitHub Pages
        run:
          ./scripts/publish_docs.sh

  clojars:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Deploy to clojars
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_TOKEN: ${{ secrets.CLOJARS_TOKEN }}
        run:
          lein deploy clojars
